# Generated by Django 3.1.2 on 2020-10-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('hospital', models.CharField(max_length=60)),
                ('contact', models.IntegerField(max_length=10)),
                ('date', models.DateField()),
                ('img', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
