# Generated by Django 3.1.2 on 2020-10-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201020_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='img',
        ),
    ]
